<?php

/**
 * @file
 * Primary module hooks for Example Module module.
 */
/**
 * hool_theme
 */

  function example_module_theme($existing, $type, $theme, $path) {
      return [
          'example-add-form' => [
              'render element' => 'form',
          ],
          'example_users_theme' => [
            'render element' => 'elements',
            'variables' => [
                'data' => [],
                'positions' => [],
            ],
          ]
      ];
  }




